### ISSUE TITLE
"none" results in the report

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#22]
Hey Dan,

First proper noun enabled report I generated ran fine. I then generated a conc of the fiction text I've been using, but there is an anomaly in the report file. A bunch of difficulty ranking are reported as "None"

![image](https://cloud.githubusercontent.com/assets/14303315/10624988/9273087a-77fa-11e5-8eab-89b03b43a9c8.png)

![image](https://cloud.githubusercontent.com/assets/14303315/10624990/9d8ade04-77fa-11e5-8d50-2822ca2b16f7.png)

Good news is, the proper noun handling seems to be working a treat! 

https://www.dropbox.com/s/635besl2d9m2zaq/OB_BUGR_18.rar?dl=0

**Comment by OllyBallance** [comment]
OK, so - over the course of around 500,000 kbs of text, I;ve found the following symbols cause NONE difficult rankings in the report

” (NONE)
“ (NONE)
" (NONE)
' (NONE)

These can be stripped out before concordancing, and then running conc > report generates reports without NONE rankings in difficulty 

Here is an example of the 'issue' (note, as there is a work-around, its no big issue):

https://www.dropbox.com/s/n9fl761ktomv3bv/OB_BUGR_19.rar?dl=0

**Comment by danballance** [comment]
Hi,

I've taken a quick look at this and it looks like it was being caused by an old function from before the re-write for proper unicode support. I've removed it and I think the results look much better.

Could you pull the latest code, re-test and report back?

**Comment by OllyBallance** [comment]
Yip, that's sorted it. Generated the error again, pulled the code, reran,
NONE  results gone.

Good work!

On 3 November 2015 at 08:40, Dan Ballance <notifications@github.com> wrote:

> Hi,
>
> I've taken a quick look at this and it looks like it was being caused by
> an old function from before the re-write for proper unicode support. I've
> removed it and I think the results look much better.
>
> Could you pull the latest code, re-test and report back?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/22#issuecomment-153135505>
> .
>



--
