### ISSUE TITLE
minor character flaws

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#24]
Ok, so, in the process of running about 500,000 kb of texts, I've encountered concordance errors I attribute to the following characters

^ (regular expression error)
' (regular expression error)	

After identifying the problem characters, I stripped them from the corpus being concordanced, and they ran without issue - so, again, as there is a work around, it no biggy

Still, here are data and command line info for each

https://www.dropbox.com/s/e9qzb5v42dpqmrb/OB_BUGR_20.rar?dl=0

https://www.dropbox.com/s/3334ff59l2r9jqc/OB_BUGR_21.rar?dl=0

**Comment by danballance** [comment]
Okay, so I think this is an issue with characters that have special meanings in regular expressions not getting escaped and causing the concordance extraction to fail.

I've just tested this theory with the caret (^) symbol. These extra characters can be added to this setting:

"regex_escape_chars": "?.*$+()[]^",

So you can see here I added the caret to the end of this list of characters and on my machine at least this ran correctly without an error.

I'm just going to look at your issue 21 now. I am not sure the single quote is the issue in this one. Will take a look now.

**Comment by danballance** [comment]
I'm having some trouble re-creating this issue actually - at least in your second example. Is it possible that my other fix has for "None" in reports has resolved this issue too?

That might be overly optimistic of me and we could be looking at another Windows/Linux difference.

I have just pushed a new version with a slightly improved error message. Could you re-test and see if you get a more useful error message? I'm hoping the error message will also include the regex pattern that failed. This should hopefully give us the clue we need to solve the issue.

**Comment by OllyBallance** [comment]
Hi Dan,

This is re issue 24 right? The fix of adding to "the regular expression escape list" for the NONE issue sounds very reasonable to me as, if memory serves, the error report says sth about unable to "extract with regular expressions" - will check it out now

**Comment by OllyBallance** [comment]
OK, with the config changed, ran without error (though had 1% partition misses, whatever they are!) - and no NONE rankings either!

Awesome!

**Comment by danballance** [comment]
(Sorry I meant your OB_BUGR_21 download, but that was confusing terminology!)

Re the partition misses - I've explained what that means in the wiki section. I'm assuming you have read the stuff I've been adding to the wiki section? ;-)

They are nothing to worry about anyway. Breaking the text into partitions was a way to speed up the regular expression searches. That means 1% of regex searches had to fall back to searching the whole document (muxh slower, but not too bad if only 1% of citations had to do this). If you needed to you could tweak the number of partitions to improve performance on this size of corpus. (Ultimately the best number of partitions could be guessed after reading the corpus, but ATM it's list a dumb process that gets this figure from the configuration settings)

**Comment by OllyBallance** [comment]
I read the wiki at one point - but I don't regularly check it. But this is
probably just a case of me having read and not taken in - I knew about the
partitioning, I just wasn't sure what a 'partition miss' was.

If it;s just a speed thing, then its no worries - but sounds like it could
help with memory errors too, right?

On 3 November 2015 at 19:44, Dan Ballance <notifications@github.com> wrote:

> (Sorry I meant your OB_BUGR_21 download, but that was confusing
> terminology!)
>
> Re the partition misses - I've explained what that means in the wiki
> section. I'm assuming you have read the stuff I've been adding to the wiki
> section? ;-)
>
> They are nothing to worry about anyway. Breaking the text into partitions
> was a way to speed up the regular expression searches. That means 1% of
> regex searches had to fall back to searching the whole document (muxh
> slower, but not too bad if only 1% of citations had to do this). If you
> needed to you could tweak the number of partitions to improve performance
> on this size of corpus. (Ultimately the best number of partitions could be
> guessed after reading the corpus, but ATM it's list a dumb process that
> gets this figure from the configuration settings)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153260239>
> .
>



--

**Comment by OllyBallance** [comment]
OK, this is weird, after adding those characters to the config file (allowing W_BNC_D to run), I was not able to run W_BNC_A_i - until that is I removed those characters from the config (as it had been previously, and so was bale to run once more)...

This seems super weird to me, and I guess this constitutes a re-open - unless I'm missing something obvious (50-50?) 

https://www.dropbox.com/s/rs93b9bn0wvtqcu/W_BNC_A_i.rar?dl=0

**Comment by danballance** [comment]
Yep, should definitely re-open, even if you're not 100% sure - it just pushes it back into the queue to be looked at again.

 Taking a look at this now.

**Comment by danballance** [comment]
Since we're dealing with changes to your config file, it might be worth me just checking your config file to be sure you are running with the same settings as well. Can you send me a before and after over?

Also say same error code. I thought I'd added some extra debugging to give the error along with the regex that caused the problem. Any chance you can send me the screen shot that you usually do? They are really useful and I always look at them. I might be something in it that doesn't stand out to you. You definitely pulled the latest code before running it? I was hoping there would be a more useful stack trace this time.

**Comment by danballance** [comment]
Oh, I also don't know what search term word you ran it against.

Don't forget I need to exactly re-create what you did to properly investigate an issue :)

**Comment by OllyBallance** [comment]
Yeah, sorry - yesterday was a very dispiriting day. I ended up manually
editing a file and somehow breaking it so it no longer ran :_( I'll try and
trace back what I did and send you a proper report on it.

You fancy a chat?

On 5 November 2015 at 09:02, Dan Ballance <notifications@github.com> wrote:

> Oh, I also don't know what search term word you ran it against.
>
> Don't forget I need to exactly re-create what you did to properly
> investigate an issue :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153847145>
> .
>



--

**Comment by danballance** [comment]
Could try Skype in a bit but can't do it at the same time as I run the concordance parser - not enough resources. Just running W_BNC_A_i with and without caret now.

One thing that stands out to me was you said "those characters" - plural. But I thought I'd only suggested the caret? The single quote sounds like a red herring or a different issue - it shouldn't need to be added to regex escapes and could in fact break things. 

Can you just paste your config here maybe?

**Comment by OllyBallance** [comment]
{
    "general": {
        "encoding": "utf-8",
        "target": "windows",
        "concordance_mode": "concordance_width",
        "parser_output": "output.txt",
        "report_input": "output.txt",
        "report_output": "report.csv",
        "citations": 1000,
        "select_citation_method": "top",
        "prepfile": "prepare.txt",
        "errorsfile": "encoding_errors.txt",
        "partitions": 10
    },
    "concordance": {
        "regex_escape_chars": "?.*$+()[]",
        "regex_is_char": "[\\w'\\-]",
        "regex_start_right_concordance": "{0}\\s*{1}\\s*",
        "regex_start_right_one_token_concordance": "{0}\\s*{1}",
        "regex_end_left_concordance": "{0}\\s*{1}",
        "regex_end_right_concordance": "{0}",
        "regex_other_concordance": "{0}\\s*"
    },
    "concordance_width": {
        "width": 150
    },
    "concordance_sentences": {
        "sentences": 1
    },
    "pickle_report": {
        "pickle_file_name": "word_lists.pickled",
        "word_list_folder": "base_word_lists",
        "proper_noun_file": "properNouns.txt",
        "pattern": "basewrd{0}.txt",
        "number_of_lists": 28,
        "regex_extract_list_word": "[\\w]+",
        "regex_is_word": "[\\w'\\-]+",
        "exclusion_tokens": "-",
        "non_possessive_s_token": "it,there,he,she,who,what",
        "difficulty_threshold": 0.95
    }
}


On 5 November 2015 at 09:19, Dan Ballance <notifications@github.com> wrote:

> Could try Skype in a bit but can't do it at the same time as I run the
> concordance parser - not enough resources. Just running W_BNC_A_i with and
> without caret now.
>
> One thing that stands out to me was you said "those characters" - plural.
> But I thought I'd only suggested the caret? The single quote sounds like a
> red herring or a different issue - it shouldn't need to be added to regex
> escapes and could in fact break things.
>
> Can you just paste your config here maybe?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153851062>
> .
>



--

**Comment by OllyBallance** [comment]
Yeah, I added both the caret and an apostrophe (cos one file that had
generated that error had needed apostrophes removed)

On 5 November 2015 at 09:23, Olly Ballance <ollyballance@gmail.com> wrote:

> {
>     "general": {
>         "encoding": "utf-8",
>         "target": "windows",
>         "concordance_mode": "concordance_width",
>         "parser_output": "output.txt",
>         "report_input": "output.txt",
>         "report_output": "report.csv",
>         "citations": 1000,
>         "select_citation_method": "top",
>         "prepfile": "prepare.txt",
>         "errorsfile": "encoding_errors.txt",
>         "partitions": 10
>     },
>     "concordance": {
>         "regex_escape_chars": "?.*$+()[]",
>         "regex_is_char": "[\\w'\\-]",
>         "regex_start_right_concordance": "{0}\\s*{1}\\s*",
>         "regex_start_right_one_token_concordance": "{0}\\s*{1}",
>         "regex_end_left_concordance": "{0}\\s*{1}",
>         "regex_end_right_concordance": "{0}",
>         "regex_other_concordance": "{0}\\s*"
>     },
>     "concordance_width": {
>         "width": 150
>     },
>     "concordance_sentences": {
>         "sentences": 1
>     },
>     "pickle_report": {
>         "pickle_file_name": "word_lists.pickled",
>         "word_list_folder": "base_word_lists",
>         "proper_noun_file": "properNouns.txt",
>         "pattern": "basewrd{0}.txt",
>         "number_of_lists": 28,
>         "regex_extract_list_word": "[\\w]+",
>         "regex_is_word": "[\\w'\\-]+",
>         "exclusion_tokens": "-",
>         "non_possessive_s_token": "it,there,he,she,who,what",
>         "difficulty_threshold": 0.95
>     }
> }
>
>
> On 5 November 2015 at 09:19, Dan Ballance <notifications@github.com>
> wrote:
>
>> Could try Skype in a bit but can't do it at the same time as I run the
>> concordance parser - not enough resources. Just running W_BNC_A_i with and
>> without caret now.
>>
>> One thing that stands out to me was you said "those characters" - plural.
>> But I thought I'd only suggested the caret? The single quote sounds like a
>> red herring or a different issue - it shouldn't need to be added to regex
>> escapes and could in fact break things.
>>
>> Can you just paste your config here maybe?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153851062>
>> .
>>
>
>
>
> --
>
>


--

**Comment by OllyBallance** [comment]
Ok, so ran fine just adding the carrot

{
    "general": {
        "encoding": "utf-8",
        "target": "windows",
        "concordance_mode": "concordance_width",
        "parser_output": "output.txt",
        "report_input": "output.txt",
        "report_output": "report.csv",
        "citations": 1000,
        "select_citation_method": "top",
        "prepfile": "prepare.txt",
        "errorsfile": "encoding_errors.txt",
        "partitions": 10
    },
    "concordance": {
        "regex_escape_chars": "?.*$+()[]^",
        "regex_is_char": "[\\w'\\-]",
        "regex_start_right_concordance": "{0}\\s*{1}\\s*",
        "regex_start_right_one_token_concordance": "{0}\\s*{1}",
        "regex_end_left_concordance": "{0}\\s*{1}",
        "regex_end_right_concordance": "{0}",
        "regex_other_concordance": "{0}\\s*"
    },
    "concordance_width": {
        "width": 150
    },
    "concordance_sentences": {
        "sentences": 1
    },
    "pickle_report": {
        "pickle_file_name": "word_lists.pickled",
        "word_list_folder": "base_word_lists",
        "proper_noun_file": "properNouns.txt",
        "pattern": "basewrd{0}.txt",
        "number_of_lists": 28,
        "regex_extract_list_word": "[\\w]+",
        "regex_is_word": "[\\w'\\-]+",
        "exclusion_tokens": "-",
        "non_possessive_s_token": "it,there,he,she,who,what",
        "difficulty_threshold": 0.95
    }
}

On 5 November 2015 at 09:24, Olly Ballance <ollyballance@gmail.com> wrote:

> Yeah, I added both the caret and an apostrophe (cos one file that had
> generated that error had needed apostrophes removed)
>
> On 5 November 2015 at 09:23, Olly Ballance <ollyballance@gmail.com> wrote:
>
>> {
>>     "general": {
>>         "encoding": "utf-8",
>>         "target": "windows",
>>         "concordance_mode": "concordance_width",
>>         "parser_output": "output.txt",
>>         "report_input": "output.txt",
>>         "report_output": "report.csv",
>>         "citations": 1000,
>>         "select_citation_method": "top",
>>         "prepfile": "prepare.txt",
>>         "errorsfile": "encoding_errors.txt",
>>         "partitions": 10
>>     },
>>     "concordance": {
>>         "regex_escape_chars": "?.*$+()[]",
>>         "regex_is_char": "[\\w'\\-]",
>>         "regex_start_right_concordance": "{0}\\s*{1}\\s*",
>>         "regex_start_right_one_token_concordance": "{0}\\s*{1}",
>>         "regex_end_left_concordance": "{0}\\s*{1}",
>>         "regex_end_right_concordance": "{0}",
>>         "regex_other_concordance": "{0}\\s*"
>>     },
>>     "concordance_width": {
>>         "width": 150
>>     },
>>     "concordance_sentences": {
>>         "sentences": 1
>>     },
>>     "pickle_report": {
>>         "pickle_file_name": "word_lists.pickled",
>>         "word_list_folder": "base_word_lists",
>>         "proper_noun_file": "properNouns.txt",
>>         "pattern": "basewrd{0}.txt",
>>         "number_of_lists": 28,
>>         "regex_extract_list_word": "[\\w]+",
>>         "regex_is_word": "[\\w'\\-]+",
>>         "exclusion_tokens": "-",
>>         "non_possessive_s_token": "it,there,he,she,who,what",
>>         "difficulty_threshold": 0.95
>>     }
>> }
>>
>>
>> On 5 November 2015 at 09:19, Dan Ballance <notifications@github.com>
>> wrote:
>>
>>> Could try Skype in a bit but can't do it at the same time as I run the
>>> concordance parser - not enough resources. Just running W_BNC_A_i with and
>>> without caret now.
>>>
>>> One thing that stands out to me was you said "those characters" -
>>> plural. But I thought I'd only suggested the caret? The single quote sounds
>>> like a red herring or a different issue - it shouldn't need to be added to
>>> regex escapes and could in fact break things.
>>>
>>> Can you just paste your config here maybe?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153851062>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>
>
> --
>
>


--

**Comment by danballance** [comment]
Hmm, so I've just run W_BNC_A_i with and without caret on my machine without an error.

Going to have to ask you to run it again I think and do my a full debug far file with everything in it plus screen shot please. Then hopefully I can recreate the issue this end.

**Comment by OllyBallance** [comment]
btw - did Elsie get her Minecraft book?

Ok - yeah, its not the carrot thats the problem, its the stick, as you
thought:

{
    "general": {
        "encoding": "utf-8",
        "target": "windows",
        "concordance_mode": "concordance_width",
        "parser_output": "output.txt",
        "report_input": "output.txt",
        "report_output": "report.csv",
        "citations": 1000,
        "select_citation_method": "top",
        "prepfile": "prepare.txt",
        "errorsfile": "encoding_errors.txt",
        "partitions": 10
    },
    "concordance": {
        "regex_escape_chars": "?.*$+()'[]^",
        "regex_is_char": "[\\w'\\-]",
        "regex_start_right_concordance": "{0}\\s*{1}\\s*",
        "regex_start_right_one_token_concordance": "{0}\\s*{1}",
        "regex_end_left_concordance": "{0}\\s*{1}",
        "regex_end_right_concordance": "{0}",
        "regex_other_concordance": "{0}\\s*"
    },
    "concordance_width": {
        "width": 150
    },
    "concordance_sentences": {
        "sentences": 1
    },
    "pickle_report": {
        "pickle_file_name": "word_lists.pickled",
        "word_list_folder": "base_word_lists",
        "proper_noun_file": "properNouns.txt",
        "pattern": "basewrd{0}.txt",
        "number_of_lists": 28,
        "regex_extract_list_word": "[\\w]+",
        "regex_is_word": "[\\w'\\-]+",
        "exclusion_tokens": "-",
        "non_possessive_s_token": "it,there,he,she,who,what",
        "difficulty_threshold": 0.95
    }
}

[image: Inline images 1]

On 5 November 2015 at 09:29, Dan Ballance <notifications@github.com> wrote:

> Hmm, so I've just run W_BNC_A_i with and without caret on my machine
> without an error.
>
> Going to have to ask you to run it again I think and do my a full debug
> far file with everything in it plus screen shot please. Then hopefully I
> can recreate the issue this end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153853428>
> .
>



--

**Comment by OllyBallance** [comment]
When I add in an apostrophe to the config, it generates that error

On 5 November 2015 at 09:31, Olly Ballance <ollyballance@gmail.com> wrote:

> btw - did Elsie get her Minecraft book?
>
> Ok - yeah, its not the carrot thats the problem, its the stick, as you
> thought:
>
> {
>     "general": {
>         "encoding": "utf-8",
>         "target": "windows",
>         "concordance_mode": "concordance_width",
>         "parser_output": "output.txt",
>         "report_input": "output.txt",
>         "report_output": "report.csv",
>         "citations": 1000,
>         "select_citation_method": "top",
>         "prepfile": "prepare.txt",
>         "errorsfile": "encoding_errors.txt",
>         "partitions": 10
>     },
>     "concordance": {
>         "regex_escape_chars": "?.*$+()'[]^",
>         "regex_is_char": "[\\w'\\-]",
>         "regex_start_right_concordance": "{0}\\s*{1}\\s*",
>         "regex_start_right_one_token_concordance": "{0}\\s*{1}",
>         "regex_end_left_concordance": "{0}\\s*{1}",
>         "regex_end_right_concordance": "{0}",
>         "regex_other_concordance": "{0}\\s*"
>     },
>     "concordance_width": {
>         "width": 150
>     },
>     "concordance_sentences": {
>         "sentences": 1
>     },
>     "pickle_report": {
>         "pickle_file_name": "word_lists.pickled",
>         "word_list_folder": "base_word_lists",
>         "proper_noun_file": "properNouns.txt",
>         "pattern": "basewrd{0}.txt",
>         "number_of_lists": 28,
>         "regex_extract_list_word": "[\\w]+",
>         "regex_is_word": "[\\w'\\-]+",
>         "exclusion_tokens": "-",
>         "non_possessive_s_token": "it,there,he,she,who,what",
>         "difficulty_threshold": 0.95
>     }
> }
>
> [image: Inline images 1]
>
> On 5 November 2015 at 09:29, Dan Ballance <notifications@github.com>
> wrote:
>
>> Hmm, so I've just run W_BNC_A_i with and without caret on my machine
>> without an error.
>>
>> Going to have to ask you to run it again I think and do my a full debug
>> far file with everything in it plus screen shot please. Then hopefully I
>> can recreate the issue this end.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153853428>
>> .
>>
>
>
>
> --
>
>


--

**Comment by OllyBallance** [comment]
But it wasn't this file that apostrophe was causing a problem in anyway -
so it doesn't need to be in.

The only problem with deleting it manually is it then affects how
contracted forms are represented

On 5 November 2015 at 09:32, Olly Ballance <ollyballance@gmail.com> wrote:

> When I add in an apostrophe to the config, it generates that error
>
> On 5 November 2015 at 09:31, Olly Ballance <ollyballance@gmail.com> wrote:
>
>> btw - did Elsie get her Minecraft book?
>>
>> Ok - yeah, its not the carrot thats the problem, its the stick, as you
>> thought:
>>
>> {
>>     "general": {
>>         "encoding": "utf-8",
>>         "target": "windows",
>>         "concordance_mode": "concordance_width",
>>         "parser_output": "output.txt",
>>         "report_input": "output.txt",
>>         "report_output": "report.csv",
>>         "citations": 1000,
>>         "select_citation_method": "top",
>>         "prepfile": "prepare.txt",
>>         "errorsfile": "encoding_errors.txt",
>>         "partitions": 10
>>     },
>>     "concordance": {
>>         "regex_escape_chars": "?.*$+()'[]^",
>>         "regex_is_char": "[\\w'\\-]",
>>         "regex_start_right_concordance": "{0}\\s*{1}\\s*",
>>         "regex_start_right_one_token_concordance": "{0}\\s*{1}",
>>         "regex_end_left_concordance": "{0}\\s*{1}",
>>         "regex_end_right_concordance": "{0}",
>>         "regex_other_concordance": "{0}\\s*"
>>     },
>>     "concordance_width": {
>>         "width": 150
>>     },
>>     "concordance_sentences": {
>>         "sentences": 1
>>     },
>>     "pickle_report": {
>>         "pickle_file_name": "word_lists.pickled",
>>         "word_list_folder": "base_word_lists",
>>         "proper_noun_file": "properNouns.txt",
>>         "pattern": "basewrd{0}.txt",
>>         "number_of_lists": 28,
>>         "regex_extract_list_word": "[\\w]+",
>>         "regex_is_word": "[\\w'\\-]+",
>>         "exclusion_tokens": "-",
>>         "non_possessive_s_token": "it,there,he,she,who,what",
>>         "difficulty_threshold": 0.95
>>     }
>> }
>>
>> [image: Inline images 1]
>>
>> On 5 November 2015 at 09:29, Dan Ballance <notifications@github.com>
>> wrote:
>>
>>> Hmm, so I've just run W_BNC_A_i with and without caret on my machine
>>> without an error.
>>>
>>> Going to have to ask you to run it again I think and do my a full debug
>>> far file with everything in it plus screen shot please. Then hopefully I
>>> can recreate the issue this end.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153853428>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>
>
> --
>
>


--

**Comment by danballance** [comment]
Yeah, I don't want you to be deleting stuff manually. Can you do a full debug report as you used to with the error you are getting running it with the apostrophes in the corpus please?

**Comment by danballance** [comment]
BTW you know your document A is not in utf-8 format according to my machine?

dan@awesome-parser$ file -bi W_BNC_A_i.txt 
text/plain; charset=iso-8859-1

**Comment by OllyBallance** [comment]
hmm - strange. I've converted it now, will see if it still generates error
and if does, send bug report

On 5 November 2015 at 09:48, Dan Ballance <notifications@github.com> wrote:

> BTW you know your document A is not in utf-8 format according to my
> machine?
>
> dan@awesome-parser$ file -bi W_BNC_A_i.txt
> text/plain; charset=iso-8859-1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153859496>
> .
>



--

**Comment by OllyBallance** [comment]
omg - ok, so I wasn't running the latest code (shame, shame, shame) - just
double checked and found there were changes to pull :-(

On 5 November 2015 at 09:44, Dan Ballance <notifications@github.com> wrote:

> Yeah, I don't want you to be deleting stuff manually. Can you do a full
> debug report as you used to with the error you are getting running it with
> the apostrophes in the corpus please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/24#issuecomment-153857296>
> .
>



--

**Comment by OllyBallance** [comment]
![image](https://cloud.githubusercontent.com/assets/14303315/10951861/adaccad0-83a4-11e5-9827-bd770af13e8a.png)

https://www.dropbox.com/s/ma73pzhcwovhqix/OB_BUGR_23.rar?dl=0

**Comment by danballance** [comment]
I think this is solved by adding common regex meta characters to ["concordance"]["regex_escape_chars"]
