### ISSUE TITLE
comma anomaly in report

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#25]
Hi, I've noticed two words being mis-rated in the report - in both cases it occurs when a the citation finishes with a comma

Example 1. not necessarily result in increased propulsion, however. Constipating drugs such as opioids increase motility while inhibiting propulsive activity, ('activity' listed as Other/offlist)

Example 2. continues to monitor the patient condition, prescribing any necessary drugs, such as those needed to control high blood pressure. Most importantly, ('importantly' listed as Other/offlist)

Corpus = W_BNC_A_i
Word = drugs
Config width = 150

the file is here:

https://www.dropbox.com/s/suuvi5r025zqabl/OB_BUGR_22.rar?dl=0

**Comment by danballance** [comment]
I think this is solved by the improved regex from issue #26. Please do re-open if I'm wrong.
