### ISSUE TITLE
First data set processed!

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#27]
Hey,

So, I think I've just run my first data set successfully, and have a system to now run whatever else I need (see attached, if you've nothing better to do ;-).

1) delete from corpus: ’  '  … — - ,
2) Run and see if any regex errors are generated - if so, track down and add char to config
3) Run and inspect 'other' column
4) edit typos in text, append misfiled items to word lists
5) repickle
6) run again
7) done!

Thanks so much Dan, I'd never have got here without you!

Olly

https://www.dropbox.com/s/vk1ip1sgam1w5nx/18_TEXTS%20as.txt?dl=0

https://www.dropbox.com/s/dag64p9awahs23c/18_TEXTS%20as.xlsx?dl=0

https://www.dropbox.com/s/a3aqz81l0xipccz/18_texts.txt?dl=0

**Comment by OllyBallance** [comment]
ps: both issues with punctuation affecting counts and crashes due to regex extraction failures seem to be circumvented following this procedure :-)

**Comment by danballance** [comment]
Okay that's good news. I'd rather you didn't have to do step one. I think
you have another ticket open for the hyphens, so I'll look at that there.
But what is happening with the 2 types of single quotes? I don't think you
should have to be deleting those by hand. Does one of those Dropbox links
include a corpus with these problem characters? I'd like to get step one
properly automated for you.

With step 2 I just think you will collect a really good set of escape
characters that work for you over time and eventually you won't need to do
that step any more. Don't forget - including a character in there that has
no special meaning in regular expressions will break the code, as was the
case with single quotes. (In that ticket I've sent you a link to a regex
cheatsheet - there's only quite a limited set of characters with special
meanings)

**Comment by OllyBallance** [comment]
I realise from a purist perspective it may not seem ideal, but I think
it'll work - and I think I've imposed on you enough for the time being!

I think pretty much any corpus generates these problems at present - but
just for the record, BUGR_26/issue 26 is an exmaple of this I think...

On 7 November 2015 at 18:31, Dan Ballance <notifications@github.com> wrote:

> Okay that's good news. I'd rather you didn't have to do step one. I think
> you have another ticket open for the hyphens, so I'll look at that there.
> But what is happening with the 2 types of single quotes? I don't think you
> should have to be deleting those by hand. Does one of those Dropbox links
> include a corpus with these problem characters? I'd like to get step one
> properly automated for you.
>
> With step 2 I just think you will collect a really good set of escape
> characters that work for you over time and eventually you won't need to do
> that step any more. Don't forget - including a character in there that has
> no special meaning in regular expressions will break the code, as was the
> case with single quotes. (In that ticket I've sent you a link to a regex
> cheatsheet - there's only quite a limited set of characters with special
> meanings)
>
> On Sat, 7 Nov 2015 01:57 OllyBallance <notifications@github.com> wrote:
>
> > Hey,
> >
> > So, I think I've just run my first data set successfully, and have a
> > system to now run whatever else I need (see attached, if you've nothing
> > better to do ;-).
> >
> > 1) delete from corpus: ’ ' … — - ,
> > 2) Run and see if any regex errors are generated - if so, track down and
> > add char to config
> > 3) Run and inspect 'other' column
> > 4) edit typos in text, append misfiled items to word lists
> > 5) repickle
> > 6) run again
> > 7) done!
> >
> > Thanks so much Dan, I'd never have got here without you!
> >
> > Olly
> >
> > https://www.dropbox.com/s/vk1ip1sgam1w5nx/18_TEXTS%20as.txt?dl=0
> >
> > https://www.dropbox.com/s/dag64p9awahs23c/18_TEXTS%20as.xlsx?dl=0
> >
> > https://www.dropbox.com/s/a3aqz81l0xipccz/18_texts.txt?dl=0
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/danballance/awesome-parser/issues/27>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/27#issuecomment-154624849>
> .
>



--

**Comment by OllyBallance** [comment]
Wills down with a horrible cough again :_(

But I just made pizza :-)

On 7 November 2015 at 18:31, Dan Ballance <notifications@github.com> wrote:

> Okay that's good news. I'd rather you didn't have to do step one. I think
> you have another ticket open for the hyphens, so I'll look at that there.
> But what is happening with the 2 types of single quotes? I don't think you
> should have to be deleting those by hand. Does one of those Dropbox links
> include a corpus with these problem characters? I'd like to get step one
> properly automated for you.
>
> With step 2 I just think you will collect a really good set of escape
> characters that work for you over time and eventually you won't need to do
> that step any more. Don't forget - including a character in there that has
> no special meaning in regular expressions will break the code, as was the
> case with single quotes. (In that ticket I've sent you a link to a regex
> cheatsheet - there's only quite a limited set of characters with special
> meanings)
>
> On Sat, 7 Nov 2015 01:57 OllyBallance <notifications@github.com> wrote:
>
> > Hey,
> >
> > So, I think I've just run my first data set successfully, and have a
> > system to now run whatever else I need (see attached, if you've nothing
> > better to do ;-).
> >
> > 1) delete from corpus: ’ ' … — - ,
> > 2) Run and see if any regex errors are generated - if so, track down and
> > add char to config
> > 3) Run and inspect 'other' column
> > 4) edit typos in text, append misfiled items to word lists
> > 5) repickle
> > 6) run again
> > 7) done!
> >
> > Thanks so much Dan, I'd never have got here without you!
> >
> > Olly
> >
> > https://www.dropbox.com/s/vk1ip1sgam1w5nx/18_TEXTS%20as.txt?dl=0
> >
> > https://www.dropbox.com/s/dag64p9awahs23c/18_TEXTS%20as.xlsx?dl=0
> >
> > https://www.dropbox.com/s/a3aqz81l0xipccz/18_texts.txt?dl=0
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/danballance/awesome-parser/issues/27>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/27#issuecomment-154624849>
> .
>



--

**Comment by danballance** [comment]
Okay so your 1st step should be no longer and the second step shouldn't hit you unless some very rate regex character hits you. I think you have them all in the escape regex now.

Closing this ticket and hoping you're good to go for a while now :)

**Comment by OllyBallance** [comment]
Awesome - I'll give this a try when Will an Eva go out a bit later

On 8 November 2015 at 08:56, Dan Ballance <notifications@github.com> wrote:

> Okay so your 1st step should be no longer and the second step shouldn't
> hit you unless some very rate regex character hits you. I think you have
> them all in the escape regex now.
>
> Closing this ticket and hoping you're good to go for a while now :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/27#issuecomment-154743291>
> .
>



--
