### ISSUE TITLE
word list rankings of apostrophe strings  

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#28]
Hey,

So that latest batch of changes all worked really well, except adding words that include apostrophes to the wordlists doesn't seem to work. For example, I add <n't> to word list one, but on the report it still comes out as other (see attached). 

Here's an example:

![image](https://cloud.githubusercontent.com/assets/14303315/11017969/dd18cede-8617-11e5-8a5c-4011dcbcdde1.png)

https://www.dropbox.com/s/vxxzbpfd100cjf0/OB_BUGR_27.rar?dl=0

**Comment by danballance** [comment]
Okay that makes sense. I'm not sure the regex for the word lists currently
allows apostrophes. I'll take a quick look now - should be a quick fix
(famous last words lol)

**Comment by danballance** [comment]
Okay, so this is just a simple addition to the regex in the config file. I've updated a pushed the example file as well though.

"regex_extract_list_word": "[\\w']+",

Seems to work for me, let me know how you get on. I'll close for now, do re-open if it's still not working for you :)

**Comment by OllyBallance** [comment]
Nice one - worked a treat :-)

On 8 November 2015 at 22:15, Dan Ballance <notifications@github.com> wrote:

> Okay, so this is just a simple addition to the regex in the config file.
> I've updated a pushed the example file as well though.
>
> "regex_extract_list_word": "[\w']+",
>
> Seems to work for me, let me know how you get on. I'll close for now, do
> re-open if it's still not working for you :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/28#issuecomment-154790640>
> .
>



--

**Comment by danballance** [comment]
:+1:
