### ISSUE TITLE
full stopped output

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#29]
Hi Dan,

A small thing that would really help me would be for the concordance output (the .txt file generated) to put a full-stop at the end of every citation.

The reason is as follows. I can load the concordance output generated into another program that will analyse the citations for conc_grams (flexible co-occurrences of words) - and I can set it not to look over certain boundaries (which is desirable). 

The boundary options are: 
- no limits
- stop at punctuation break 
- stop at sentence break
- stop at paragraph break
- stop at heading break
- stop at section break
- stop at end of text

I'm thinking of using 'stop at sentence break' - as presumably this will not identify co-occurrences of words with a full-stop in the middle (many citations show the end of one sentence and the beginning of another) - adding a full stop to the end of every citation will also stop the program identifying co-occurrences across citations.

For some reason I think this will be easy to do (famous last words)...

Cheers,

Olly

**Comment by danballance** [comment]
That should be pretty straight forward. I'll try and add it as a
configurable option - so you can turn the behaviour on and off.

**Comment by danballance** [comment]
That should be working for you now if you pull the latest code :)

So I have added a new config setting in the "general" section called citation_format. It uses a standard python string formatting technique where {0} will be replaced with your raw, unmodified citation. To make it output each citation with a following fullstop, the setting you need would be:

{0}.

Say for some reason you need to wrap each citation in pipes, then you could use:

|{0}|

Does that make sense? I'll close for now, feel free to re-open if you hit any issue!

**Comment by OllyBallance** [comment]
Thanks Dan, that's worked a treat (and very clearly explained once again).

Sorry its taken  me a while to get back to you on this but been struggling
a little.

Just FYI, here's some of the data I've collected so far:

Texts

Word

Citations

AVG 95% lvl

95% lvl SD

TTR

STTR

18 (1m)

as

8242

3.7

3.3

6.17

38.93

18 (1m)

at

7241

3.7

3.5

6.78

41.36

18 (1m)

by

2476

4.3

3.5

13.37

45.21

18 (1m)

in

13100

3.9

3.5

5.1

41.68

18 (1m)

of

19067

4.1

3.5

4.23

40.32

18 (1m)

on

6558

3.7

3.2

7.43

42.64





56,685 OA

3.9 M

3.42 M

1.83 OA

41.04 OA





























74 (1m)

as

5766

3.4

3.5

7.83

37.91

74 (1m)

at

7572

3.2

3.6

6.54

39.02

74 (1m)

by

2475

3.9

4.2

13.94

44.92

74 (1m)

in

15595

3.5

3.7

4.8

38.58

74 (1m)

of

19566

3.6

3.6

4.48

37.75

74 (1m)

on

7954

3.4

3.5

6.82

40.44





58,928 OA

3.65 M

3.68 M

1.94 OA

38.81 OA





























On 14 November 2015 at 23:33, Dan Ballance <notifications@github.com> wrote:

> That should be working for you now if you pull the latest code :)
>
> So I have added a new config setting in the "general" section called
> citation_format. It uses a standard python string formatting technique
> where {0} will be replaced with your raw, unmodified citation. To make it
> output each citation with a following fullstop, the setting you need would
> be:
>
> {0}.
>
> Say for some reason you need to wrap each citation in pipes, then you
> could use:
>
> |{0}|
>
> Does that make sense? I'll close for now, feel free to re-open if you hit
> any issue!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danballance/awesome-parser/issues/29#issuecomment-156682161>
> .
>



--

**Comment by danballance** [comment]
Formatting pretty crazy on here. Feel free to ping me a non-github email with what you have been looking at so far. Would be interesting to see how you're getting along :)
