### ISSUE TITLE
Proper noun handling for report

### ISSUE THREAD

**Issue by OllyBallance** [danballance/awesome-parser#3]
Hi Dan,

The file attached is a list of proper nouns - if at all possible, it would be good if this could be used to filter results (not for the concordance, but for the frequency level counts for the report).

https://www.dropbox.com/s/j5r7d5brerct79w/basewrd31.txt?dl=0

Ideally, it would be used something like this:

Basewrd31 contains proper nouns: 
1	(if on list 31 AND on lists 1-25 AND initial letter = capital THEN print on list 31 and EXCLUDE from calculations) 
2	(if on list 31 AND on list 1-25 AND initial letter = lower case THEN print on list 1-25 and INCLUDE in calculations) 
3	(if on list 31, and NOT on list 1-25, THEN print on list 31 and EXCLUDE from calculations) 
4a     (if not on list 31, and NOT on list 1-25 AND initial letter = capital THEN  print on list 31 and EXCLUDE from calculations)

This should catch the majority of proper nouns that are listed, though an even better version would include checks for sentence initial positions - that is, instead of 4a, use 4b (if its not too complicated/time consuming)

4b    (if not on list 31, and NOT on list 1-25 AND initial letter = capital AND it is NOT preceded by a space AS WELL AS "." OR "?" OR "!"  THEN  print on list 31 and EXCLUDE from calculations)

I hope that makes a little sense!

**Comment by danballance** [comment]
Yes, you should just add your additional vocab to the word lists and re-pickle.
